---
name: "Job status codes"

'on':
  workflow_dispatch:
  push:
    branches: ['*']

jobs:
  success-job:
    runs-on: ubuntu-latest
    steps:
      - name: Exit success
        id: vars
        run: |
          echo "Running exit 0"
          exit 0

  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Exit failure
        id: vars
        run: |
          echo "Running exit 1"
          exit 1

  variabilized-failed-job:
    runs-on: ubuntu-latest
    steps:
      - name: Exit failure
        id: vars
        run: |
          a=$(echo 5)
          echo "Running exit 5"
          exit $a
